export const INITIAL_DEPARTMENTS = [
  {
    id: 'dept-1',
    name: 'ផ្នែកបច្ចេកវិទ្យា & វិស្វកម្ម (Engineering & Tech)',
    description: 'ការអភិវឌ្ឍប្រព័ន្ធកម្មវិធី ហេដ្ឋារចនាសម្ព័ន្ធ Cloud និងប្រព័ន្ធឆ្លាតវៃ AI។',
    manager_id: 'emp-1',
    budget: 450000,
    color: '#3b82f6',
  },
  {
    id: 'dept-2',
    name: 'ផ្នែករចនា & ផលិតផល (Product & Design)',
    description: 'យុទ្ធសាស្ត្រផលិតផលឌីជីថល និងការរចនាបទពិសោធន៍អ្នកប្រើប្រាស់ UI/UX។',
    manager_id: 'emp-4',
    budget: 280000,
    color: '#8b5cf6',
  },
  {
    id: 'dept-3',
    name: 'ផ្នែកទីផ្សារ & ប្រព័ន្ធផ្សព្វផ្សាយ (Marketing & PR)',
    description: 'ការកសាងម៉ាកយីហោ ទីផ្សារឌីជីថល និងការផ្សព្វផ្សាយជាសាធារណៈ។',
    manager_id: 'emp-7',
    budget: 210000,
    color: '#ec4899',
  },
  {
    id: 'dept-4',
    name: 'ផ្នែកលក់ & អភិវឌ្ឍន៍អាជីវកម្ម (Sales & Enterprise)',
    description: 'ការគ្រប់គ្រងអតិថិជនសហគ្រាស និងការពង្រីកទីផ្សារក្នុងតំបន់។',
    manager_id: 'emp-10',
    budget: 380000,
    color: '#10b981',
  },
  {
    id: 'dept-5',
    name: 'ផ្នែកធនធានមនុស្ស & វប្បធម៌ (People & Culture)',
    description: 'ការគ្រប់គ្រងបុគ្គលិក អត្ថប្រយោជន៍ ប.ស.ស និងការអភិវឌ្ឍទេពកោសល្យ។',
    manager_id: 'emp-13',
    budget: 190000,
    color: '#f59e0b',
  },
  {
    id: 'dept-6',
    name: 'ផ្នែកគណនេយ្យ & ហិរញ្ញវត្ថុ (Finance & Legal)',
    description: 'ផែនការហិរញ្ញវត្ថុ ការទូទាត់ពន្ធ និងអនុលោមភាពច្បាប់នៅកម្ពុជា។',
    manager_id: 'emp-16',
    budget: 250000,
    color: '#6366f1',
  },
];

export const INITIAL_EMPLOYEES = [
  {
    id: 'emp-1',
    first_name: 'សុភ័ក្ត្រ',
    last_name: 'វ៉ាន់',
    email: 'van.sopheak@hestra.kh',
    phone: '+855 12 888 123',
    role: 'នាយកផ្នែកបច្ចេកវិទ្យា (VP of Engineering)',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 68000,
    join_date: '2022-03-15',
    manager_id: null,
    avatar: '/avatars/khmer_male_1.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'អ្នកជំនាញផ្នែកស្ថាបត្យកម្មប្រព័ន្ធកុំព្យូទ័រ និង Cloud Infrastructure មានបទពិសោធន៍ជាង ១២ ឆ្នាំ។',
    emergency_contact_name: 'វ៉ាន់ សុភាព (បងប្រុស)',
    emergency_contact_phone: '+855 12 999 001',
    created_at: '2022-03-15T09:00:00Z',
  },
  {
    id: 'emp-2',
    first_name: 'ធីតា',
    last_name: 'ចាន់',
    email: 'chan.thida@hestra.kh',
    phone: '+855 16 777 234',
    role: 'វិស្វករកម្មវិធីជាន់ខ្ពស់ (Lead Full-Stack)',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 48000,
    join_date: '2023-01-10',
    manager_id: 'emp-1',
    avatar: '/avatars/khmer_female_2.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'មានជំនាញខ្ពស់លើ Next.js, React, Node.js និង TypeScript ក្នុងការកសាងប្រព័ន្ធ HRMS។',
    emergency_contact_name: 'ចាន់ សុខុម (ឪពុក)',
    emergency_contact_phone: '+855 92 111 222',
    created_at: '2023-01-10T09:00:00Z',
  },
  {
    id: 'emp-3',
    first_name: 'វិសាល',
    last_name: 'សួន',
    email: 'suon.visal@hestra.kh',
    phone: '+855 70 666 345',
    role: 'វិស្វករ DevOps & Cloud Security',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Remote',
    salary: 42000,
    join_date: '2023-06-01',
    manager_id: 'emp-1',
    avatar: '/avatars/khmer_male_2.jpg',
    location: 'ខេត្តសៀមរាប (Siem Reap - WFH)',
    bio: 'អ្នកជំនាញ Kubernetes, Docker, និងស្វ័យប្រវត្តិកម្ម CI/CD សម្រាប់ប្រព័ន្ធសហគ្រាស។',
    emergency_contact_name: 'សួន ចន្ថា (ប្អូនស្រី)',
    emergency_contact_phone: '+855 88 333 444',
    created_at: '2023-06-01T09:00:00Z',
  },
  {
    id: 'emp-4',
    first_name: 'ចិន្តា',
    last_name: 'គង់',
    email: 'kong.chenda@hestra.kh',
    phone: '+855 12 555 456',
    role: 'ប្រធានផ្នែករចនា (Head of Product Design)',
    department_id: 'dept-2',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 52000,
    join_date: '2022-07-20',
    manager_id: null,
    avatar: '/avatars/khmer_female_3.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'ដឹកនាំការរចនា UI/UX បែបទំនើប ស្របតាមវប្បធម៌ និងតម្រូវការទីផ្សារនៅកម្ពុជា។',
    emergency_contact_name: 'គង់ វីរៈ (ស្វាមី)',
    emergency_contact_phone: '+855 12 444 555',
    created_at: '2022-07-20T09:00:00Z',
  },
  {
    id: 'emp-5',
    first_name: 'វណ្ណា',
    last_name: 'សេង',
    email: 'seng.vanna@hestra.kh',
    phone: '+855 98 444 567',
    role: 'អ្នកស្រាវជ្រាវផលិតផល (Principal UX Researcher)',
    department_id: 'dept-2',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 36000,
    join_date: '2023-04-12',
    manager_id: 'emp-4',
    avatar: '/avatars/khmer_male_1.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'ផ្តោតលើការសម្ភាសន៍អ្នកប្រើប្រាស់ និងការធ្វើតេស្តលទ្ធភាពប្រើប្រាស់នៃប្រព័ន្ធ HR។',
    emergency_contact_name: 'សេង សោភា (ម្តាយ)',
    emergency_contact_phone: '+855 11 555 666',
    created_at: '2023-04-12T09:00:00Z',
  },
  {
    id: 'emp-6',
    first_name: 'សុជាតា',
    last_name: 'លី',
    email: 'ly.socheata@hestra.kh',
    phone: '+855 15 333 678',
    role: 'អ្នករចនាផលិតផល (Senior Product Designer)',
    department_id: 'dept-2',
    employment_type: 'Full-Time',
    status: 'On Leave',
    salary: 34000,
    join_date: '2024-02-01',
    manager_id: 'emp-4',
    avatar: '/avatars/khmer_female_1.jpg',
    location: 'ខេត្តបាត់ដំបង (Battambang)',
    bio: 'អ្នករចនា Design System និងរូបភាពចលនាសម្រាប់គេហទំព័រ និងទូរស័ព្ទ។',
    emergency_contact_name: 'លី រតនា (បងប្រុស)',
    emergency_contact_phone: '+855 77 666 777',
    created_at: '2024-02-01T09:00:00Z',
  },
  {
    id: 'emp-7',
    first_name: 'បូរី',
    last_name: 'ឃឹម',
    email: 'khim.borey@hestra.kh',
    phone: '+855 12 222 789',
    role: 'នាយកផ្នែកទីផ្សារ (Director of Marketing)',
    department_id: 'dept-3',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 48000,
    join_date: '2022-11-15',
    manager_id: null,
    avatar: '/avatars/khmer_male_3.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'យុទ្ធសាស្ត្រទីផ្សារឌីជីថល B2B SaaS និងការពង្រឹងវត្តមានយីហោទូទាំងប្រទេសកម្ពុជា។',
    emergency_contact_name: 'ឃឹម សុខា (ភរិយា)',
    emergency_contact_phone: '+855 12 777 888',
    created_at: '2022-11-15T09:00:00Z',
  },
  {
    id: 'emp-8',
    first_name: 'មុន្នី',
    last_name: 'រ័ត្ន',
    email: 'rath.mony@hestra.kh',
    phone: '+855 93 111 890',
    role: 'អ្នកគ្រប់គ្រងមាតិកា (Content Strategist)',
    department_id: 'dept-3',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 26000,
    join_date: '2024-05-20',
    manager_id: 'emp-7',
    avatar: '/avatars/khmer_female_2.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'សរសេរអត្ថបទបច្ចេកវិទ្យា ផលិតវីដេអូ និងគ្រប់គ្រងយុទ្ធនាការលើបណ្តាញសង្គម។',
    emergency_contact_name: 'រ័ត្ន សម្បត្តិ (ឪពុក)',
    emergency_contact_phone: '+855 10 888 999',
    created_at: '2024-05-20T09:00:00Z',
  },
  {
    id: 'emp-9',
    first_name: 'ស្រីពៅ',
    last_name: 'ហេង',
    email: 'heng.sreypov@hestra.kh',
    phone: '+855 81 999 012',
    role: 'អ្នករចនាម៉ាកយីហោ (Brand Visual Designer)',
    department_id: 'dept-3',
    employment_type: 'Contract',
    status: 'Remote',
    salary: 24000,
    join_date: '2025-01-15',
    manager_id: 'emp-7',
    avatar: '/avatars/khmer_female_1.jpg',
    location: 'ខេត្តកំពត (Kampot - WFH)',
    bio: 'រចនារូបភាព ក្រាហ្វិក និងក្បូរក្បាច់បែបទំនើបសម្រាប់ឯកសារសហគ្រាស។',
    emergency_contact_name: 'ហេង ចំរើន (បងប្រុស)',
    emergency_contact_phone: '+855 97 777 666',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 'emp-10',
    first_name: 'ពិសិដ្ឋ',
    last_name: 'អ៊ុក',
    email: 'ouk.piseth@hestra.kh',
    phone: '+855 12 333 901',
    role: 'នាយកផ្នែកលក់ (VP of Enterprise Sales)',
    department_id: 'dept-4',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 65000,
    join_date: '2022-05-01',
    manager_id: null,
    avatar: '/avatars/khmer_male_1.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'មានបទពិសោធន៍ជាង ១០ ឆ្នាំ ក្នុងការចរចាកិច្ចសន្យាដំណោះស្រាយ HR ជាមួយធនាគារ និងក្រុមហ៊ុនធំៗ។',
    emergency_contact_name: 'អ៊ុក វណ្ណឌី (ភរិយា)',
    emergency_contact_phone: '+855 12 666 555',
    created_at: '2022-05-01T09:00:00Z',
  },
  {
    id: 'emp-11',
    first_name: 'សុផល',
    last_name: 'ម៉ៅ',
    email: 'mao.sophal@hestra.kh',
    phone: '+855 17 222 012',
    role: 'មន្ត្រីទំនាក់ទំនងអតិថិជន (Account Executive)',
    department_id: 'dept-4',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 32000,
    join_date: '2023-08-14',
    manager_id: 'emp-10',
    avatar: '/avatars/khmer_female_3.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'ផ្តល់ការប្រឹក្សាអំពីដំណោះស្រាយគ្រប់គ្រងប្រាក់ខែ និងវត្តមានដល់អាជីវកម្ម SMEs។',
    emergency_contact_name: 'ម៉ៅ សុគន្ធ (បងស្រី)',
    emergency_contact_phone: '+855 12 555 111',
    created_at: '2023-08-14T09:00:00Z',
  },
  {
    id: 'emp-12',
    first_name: 'សុវណ្ណ',
    last_name: 'ជា',
    email: 'chea.sovann@hestra.kh',
    phone: '+855 92 111 345',
    role: 'វិស្វករដំណោះស្រាយលក់ (Solutions Engineer)',
    department_id: 'dept-4',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 38000,
    join_date: '2024-01-08',
    manager_id: 'emp-10',
    avatar: '/avatars/khmer_male_2.jpg',
    location: 'ក្រុងព្រះសីហនុ (Sihanoukville)',
    bio: 'ជួយសម្របសម្រួលបច្ចេកទេស ការភ្ជាប់ API និងប្រព័ន្ធស្កេនមេដៃ/មុខសម្រាប់អតិថិជន។',
    emergency_contact_name: 'ជា ផល្លី (ម្តាយ)',
    emergency_contact_phone: '+855 92 444 333',
    created_at: '2024-01-08T09:00:00Z',
  },
  {
    id: 'emp-13',
    first_name: 'សារ៉ាត់',
    last_name: 'Sarath',
    email: 'sarath@hestra.kh',
    phone: '+855 12 456 789',
    role: 'ប្រធាននាយកដ្ឋានធនធានមនុស្ស (Head of HR)',
    department_id: 'dept-5',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 72000,
    join_date: '2021-10-01',
    manager_id: null,
    avatar: '/avatars/khmer_female_1.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'ដឹកនាំគោលនយោបាយធនធានមនុស្ស អនុលោមភាពច្បាប់ការងារកម្ពុជា ការធានារ៉ាប់រង ប.ស.ស និងសុខុមាលភាពបុគ្គលិក។',
    emergency_contact_name: 'សារ៉ាត់ ពិសី',
    emergency_contact_phone: '+855 12 888 777',
    created_at: '2021-10-01T09:00:00Z',
  },
  {
    id: 'emp-14',
    first_name: 'សុខុម',
    last_name: 'ព្រំ',
    email: 'prom.sokhom@hestra.kh',
    phone: '+855 16 888 234',
    role: 'មន្ត្រីជ្រើសរើសបុគ្គលិកជាន់ខ្ពស់ (Senior Recruiter)',
    department_id: 'dept-5',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 28000,
    join_date: '2023-03-20',
    manager_id: 'emp-13',
    avatar: '/avatars/khmer_female_2.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'ស្វែងរកនិងជ្រើសរើសបុគ្គលិកជំនាញ IT វិស្វករកម្មវិធី និងអ្នកដឹកនាំអាជីវកម្មឆ្នើម។',
    emergency_contact_name: 'ព្រំ វណ្ណារ៉ា (បងស្រី)',
    emergency_contact_phone: '+855 15 222 333',
    created_at: '2023-03-20T09:00:00Z',
  },
  {
    id: 'emp-15',
    first_name: 'សុគន្ធា',
    last_name: 'យឹម',
    email: 'yim.sokunthea@hestra.kh',
    phone: '+855 77 555 890',
    role: 'មន្ត្រីប្រតិបត្តិការធនធានមនុស្ស (People Operations Lead)',
    department_id: 'dept-5',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 26000,
    join_date: '2024-03-10',
    manager_id: 'emp-13',
    avatar: '/avatars/khmer_female_3.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'គ្រប់គ្រងការចុះឈ្មោះ ប.ស.ស ការឈប់សម្រាកបុណ្យជាតិ និងសកម្មភាពកម្សាន្តបុគ្គលិក។',
    emergency_contact_name: 'យឹម មុន្នី (បងប្រុស)',
    emergency_contact_phone: '+855 11 999 888',
    created_at: '2024-03-10T09:00:00Z',
  },
  {
    id: 'emp-16',
    first_name: 'គឹមឡេង',
    last_name: 'តាំង',
    email: 'tang.kimleng@hestra.kh',
    phone: '+855 12 777 901',
    role: 'នាយកហិរញ្ញវត្ថុ & ច្បាប់ (Head of Finance & Legal)',
    department_id: 'dept-6',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 62000,
    join_date: '2022-01-15',
    manager_id: null,
    avatar: '/avatars/khmer_male_3.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'គណនេយ្យករជំនាញ (CPA) គ្រប់គ្រងថវិកា ប្រាក់បៀវត្សរ៍ និងរបាយការណ៍ពន្ធនៅកម្ពុជា។',
    emergency_contact_name: 'តាំង ស្រីលីន (ភរិយា)',
    emergency_contact_phone: '+855 12 999 111',
    created_at: '2022-01-15T09:00:00Z',
  },
  {
    id: 'emp-17',
    first_name: 'ចរិយា',
    last_name: 'ស៊ុន',
    email: 'sun.chariya@hestra.kh',
    phone: '+855 95 333 456',
    role: 'អ្នកវិភាគហិរញ្ញវត្ថុជាន់ខ្ពស់ (Senior Financial Analyst)',
    department_id: 'dept-6',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 33000,
    join_date: '2023-09-01',
    manager_id: 'emp-16',
    avatar: '/avatars/khmer_female_1.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'ត្រួតពិនិត្យការទូទាត់ប្រាក់បៀវត្សរ៍ គណនាកាត់កងពន្ធលើប្រាក់បៀវត្ស និងការចំណាយក្រុមហ៊ុន។',
    emergency_contact_name: 'ស៊ុន បូរិន (ឪពុក)',
    emergency_contact_phone: '+855 12 333 222',
    created_at: '2023-09-01T09:00:00Z',
  },
  {
    id: 'emp-18',
    first_name: 'ដារ៉ា',
    last_name: 'ឌី',
    email: 'dy.dara@hestra.kh',
    phone: '+855 16 444 555',
    role: 'អ្នកអភិវឌ្ឍន៍គេហទំព័រ (Frontend Web Engineer)',
    department_id: 'dept-1',
    employment_type: 'Full-Time',
    status: 'Active',
    salary: 28000,
    join_date: '2025-06-15',
    manager_id: 'emp-2',
    avatar: '/avatars/khmer_male_2.jpg',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    bio: 'បង្កើតផ្ទាំងកម្មវិធី UI ដ៏ទំនើប ងាយស្រួលប្រើប្រាស់ និងដំណើរការបានលឿន។',
    emergency_contact_name: 'ឌី សុខេង (បងប្រុស)',
    emergency_contact_phone: '+855 98 111 444',
    created_at: '2025-06-15T09:00:00Z',
  },
];

export const INITIAL_JOB_POSTINGS = [
  {
    id: 'job-1',
    title: 'វិស្វករកម្មវិធីជាន់ខ្ពស់ Full-Stack (Next.js & TypeScript)',
    department_id: 'dept-1',
    location: 'រាជធានីភ្នំពេញ (Hybrid)',
    type: 'Full-Time',
    experience_level: 'ជាន់ខ្ពស់ / ៤+ ឆ្នាំ',
    salary_range: '$1,800 - $2,800 / ខែ',
    description: 'ដឹកនាំការកសាង និងពង្រីកប្រព័ន្ធ HESTRA HRM Web App ជាមួយ React 19, TypeScript និង Next.js។',
    requirements: 'មានបទពិសោធន៍យ៉ាងហោច ៤ ឆ្នាំជាមួយ Fullstack, Next.js, Node.js, SQL database និង Git។',
    status: 'Active',
    posted_date: '2026-08-25',
    applicants_count: 24,
  },
  {
    id: 'job-2',
    title: 'អ្នករចនាផលិតផល UI/UX (Design Systems)',
    department_id: 'dept-2',
    location: 'រាជធានីភ្នំពេញ / Remote',
    type: 'Full-Time',
    experience_level: 'មធ្យម-ជាន់ខ្ពស់ / ៣+ ឆ្នាំ',
    salary_range: '$1,200 - $2,000 / ខែ',
    description: 'ទទួលខុសត្រូវលើប្រព័ន្ធ Design System, Figma Components, និងការរចនាបទពិសោធន៍អ្នកប្រើប្រាស់។',
    requirements: 'មានស្នាដៃការងារ (Portfolio) បង្ហាញពីការរចនា Web/Mobile Apps ទំនើប និងច្បាស់លាស់។',
    status: 'Active',
    posted_date: '2026-09-01',
    applicants_count: 38,
  },
  {
    id: 'job-3',
    title: 'មន្ត្រីទំនាក់ទំនងអតិថិជនសហគ្រាស (Enterprise Sales)',
    department_id: 'dept-4',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    type: 'Full-Time',
    experience_level: 'ជាន់ខ្ពស់ / ៣+ ឆ្នាំ',
    salary_range: '$1,000 Base + Commission ខ្ពស់',
    description: 'ពង្រីកការលក់ប្រព័ន្ធគ្រប់គ្រងធនធានមនុស្សទៅកាន់ក្រុមហ៊ុនធំៗ និងធនាគារនៅកម្ពុជា។',
    requirements: 'មានបទពិសោធន៍លក់សេវាកម្ម B2B ឬ Software មានជំនាញចរចា និងទំនាក់ទំនងល្អឥតខ្ចោះ។',
    status: 'Active',
    posted_date: '2026-09-05',
    applicants_count: 19,
  },
  {
    id: 'job-4',
    title: 'មន្ត្រីទីផ្សារឌីជីថល & មាតិកា (Digital Marketing Specialist)',
    department_id: 'dept-3',
    location: 'រាជធានីភ្នំពេញ (Phnom Penh)',
    type: 'Full-Time',
    experience_level: 'មធ្យម / ២+ ឆ្នាំ',
    salary_range: '$700 - $1,200 / ខែ',
    description: 'គ្រប់គ្រងផេក Facebook, Telegram, LinkedIn, TikTok និងបង្កើតមាតិកាទាក់ទាញពី HESTRA HRM។',
    requirements: 'មានភាពច្នៃប្រឌិតខ្ពស់ ចេះរចនារូបភាព និងកាត់តវីដេអូខ្លីៗ មានជំនាញសរសេរភាសាខ្មែរបានស្ទាត់ជំនាញ។',
    status: 'Active',
    posted_date: '2026-09-10',
    applicants_count: 31,
  },
];

export const INITIAL_CANDIDATES = [
  {
    id: 'cand-1',
    job_id: 'job-1',
    name: 'ហេង រតនា (Heng Rathana)',
    email: 'heng.rathana@example.com',
    phone: '+855 12 771 889',
    stage: 'Offer',
    rating: 5,
    applied_date: '2026-08-28',
    notes: 'បានឆ្លងកាត់ការប្រឡងបច្ចេកទេសយ៉ាងឆ្នើម។ មានចំណេះដឹងជ្រៅជ្រៅលើ System Architecture និង Next.js។',
  },
  {
    id: 'cand-2',
    job_id: 'job-1',
    name: 'ស៊ិន វឌ្ឍនា (Sin Vathana)',
    email: 'sin.vathana@example.com',
    phone: '+855 16 662 778',
    stage: 'Interview',
    rating: 4,
    applied_date: '2026-09-02',
    notes: 'មានបទពិសោធន៍ ៥ ឆ្នាំនៅធនាគារក្នុងស្រុក។ កំពុងរៀបចំសម្ភាសន៍ជុំចុងក្រោយជាមួយនាយកបច្ចេកវិទ្យា។',
  },
  {
    id: 'cand-3',
    job_id: 'job-2',
    name: 'លឹម គឹមសួរ (Lim Kimsour)',
    email: 'lim.kimsour@example.com',
    phone: '+855 70 553 667',
    stage: 'Interview',
    rating: 5,
    applied_date: '2026-09-04',
    notes: 'ស្នាដៃ Figma Design ស្អាតខ្លាំង មានក្បូរក្បាច់ និង Micro-interactions បែបអន្តរជាតិ។',
  },
  {
    id: 'cand-4',
    job_id: 'job-2',
    name: 'អ៊ុំ ស្រីនិច (Oum Sreynich)',
    email: 'oum.sreynich@example.com',
    phone: '+855 15 444 556',
    stage: 'Screening',
    rating: 4,
    applied_date: '2026-09-12',
    notes: 'បានឆ្លងផុតការពិនិត្យ CV របស់មន្ត្រីជ្រើសរើសបុគ្គលិក។',
  },
  {
    id: 'cand-5',
    job_id: 'job-3',
    name: 'ឈៀង វិបុល (Chheang Vibol)',
    email: 'chheang.vibol@example.com',
    phone: '+855 12 333 445',
    stage: 'Applied',
    rating: 3,
    applied_date: '2026-09-18',
    notes: 'ប្រវត្តិរូបសង្ខេបកំពុងស្ថិតក្នុងការពិនិត្យ។ ធ្លាប់ធ្វើការនៅក្រុមហ៊ុនទូរគមនាគមន៍ធំ។',
  },
];

export const INITIAL_ANNOUNCEMENTS = [
  {
    id: 'ann-1',
    title: '🇰🇭 សេចក្តីជូនដំណឹងស្តីពីការឈប់សម្រាកក្នុងព្រះរាជពិធីបុណ្យអុំទូក បណ្តែតប្រទីប និងសំពះព្រះខែ អកអំបុក',
    content: 'សូមជម្រាបជូនដល់បុគ្គលិកទាំងអស់ឱ្យបានជ្រាបថា ក្រុមហ៊ុននឹងឈប់សម្រាកចំនួន ៣ ថ្ងៃ ក្នុងឱកាសព្រះរាជពិធីបុណ្យអុំទូក។ សូមជូនពរឱ្យបុគ្គលិកទាំងអស់មានដំណើរកម្សាន្តប្រកបដោយសុវត្ថិភាព និងសេចក្តីសប្បាយរីករាយ!',
    author_id: 'emp-13',
    category: 'Celebration',
    pinned: 1,
    created_at: '2026-09-18T10:00:00Z',
  },
  {
    id: 'ann-2',
    title: '🌸 កម្មវិធីជួបជុំសាមគ្គីភាពបុគ្គលិក អបអរសាទរពិធីបុណ្យភ្ជុំបិណ្ឌ',
    content: 'ក្រុមហ៊ុននឹងរៀបចំអាហារសាមគ្គីភាព និងពិធីសូត្រមន្តលើករាសីនៅការិយាល័យកណ្តាល ដើម្បីអបអរសាទរពិធីបុណ្យភ្ជុំបិណ្ឌប្រពៃណីជាតិខ្មែរ។ សូមអញ្ជើញបុគ្គលិកទាំងអស់ចូលរួមដោយសេចក្តីសោមនស្សរីករាយ។',
    author_id: 'emp-13',
    category: 'General',
    pinned: 1,
    created_at: '2026-09-15T14:30:00Z',
  },
  {
    id: 'ann-3',
    title: '💼 គោលការណ៍ស្តីពីអត្ថប្រយោជន៍របបសន្តិសុខសង្គម (ប.ស.ស) និងការធានារ៉ាប់រងសុខភាព',
    content: 'សូមបុគ្គលិកទាំងអស់ពិនិត្យមើលប័ណ្ណ ប.ស.ស (NSSF) របស់ខ្លួន សម្រាប់ការថែទាំសុខភាព គ្រោះថ្នាក់ការងារ និងប្រាក់សោធននិវត្តន៍ ស្របតាមច្បាប់ការងារនៃព្រះរាជាណាចក្រកម្ពុជា។',
    author_id: 'emp-15',
    category: 'Policy',
    pinned: 0,
    created_at: '2026-09-10T11:00:00Z',
  },
];

export const INITIAL_PERFORMANCE_REVIEWS = [
  {
    id: 'rev-1',
    employee_id: 'emp-2',
    reviewer_id: 'emp-1',
    review_period: 'ឆមាសទី១ ឆ្នាំ២០២៦ (Mid-Year 2026)',
    rating: 4.9,
    goals_achievement: 98,
    strengths: 'មានភាពប៉ិនប្រសប់ខ្ពស់ក្នុងការសរសេរកូដស្អាត ដឹកនាំក្រុមការងារវិស្វកម្មបានល្អ និងដោះស្រាយបញ្ហាប្រព័ន្ធបានទាន់ពេលវេលា។',
    areas_for_growth: 'បន្តពង្រឹងការបណ្តុះបណ្តាលសមាជិកក្រុមថ្មី និងការចូលរួមចែករំលែកបទពិសោធន៍ក្នុងសហគមន៍បច្ចេកវិទ្យាកម្ពុជា។',
    status: 'Completed',
    created_at: '2026-07-15T12:00:00Z',
  },
  {
    id: 'rev-2',
    employee_id: 'emp-18',
    reviewer_id: 'emp-2',
    review_period: 'ត្រីមាសទី២ ឆ្នាំ២០២៦ (Q2 2026)',
    rating: 4.7,
    goals_achievement: 95,
    strengths: 'រៀនឆាប់ចេះ យកចិត្តទុកដាក់លើព័ត៌មានលម្អិតនៃ UI/UX និងបំពេញភារកិច្ចបានលឿន។',
    areas_for_growth: 'រៀនបន្ថែមអំពីការបង្កើនប្រសិទ្ធភាពទិន្នន័យ (Performance Optimization) លើ Backend។',
    status: 'Completed',
    created_at: '2026-07-20T14:00:00Z',
  },
];
